config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  
  root 'static_pages#home'
  get 'resume' => 'static_pages#resume'
  get 'contact' => 'static_pages#contact'
  get 'instagram' => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "hello, world!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @gram = Instagram.user_recent_media('8162616', {count:40})
    @instagram = Instagram.tag_recent_media('cat',:access_token =>'8162616.789201e.f4b31eb6f1aa40eb90db7d8d6a3223e0')
    #@instagram = Instagram.tag_recent_media("cat",)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def resume
  end
  
  def about
  end
  
  def contact
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "LEK"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide(:title, 'Instagram') %>
<body>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Instagram <i class="fa fa-instagram"></i>
        </h1>
    </div>
</div>

<div class = "tagged-images-container-position">
    <% @instagram.each do |instagram| %>
    <div><%= instagram.caption.text %></div>
    <% end %>
</div>   

<div class="container" >
<% @gram.each do |instagram| %>
            <div class="col-md-3 single-portfolio col-sm-6">
                <figure class="portfolio-item">
                    <%= image_tag instagram.images.standard_resolution.url,class: "img-responsive"%>
                    <figcaption class="portfolio-details">
                        <p><%= instagram.caption.text %></p>
                    </figcaption>
                </figure>
                <a href="#"><i class="fa fa-comment-o"></i></a>
            </div>
<% end %>
</div>

</body>    

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The world's simplest application
    by <a href="https://www.linkedin.com/in/lily-kaplan-15b1a558">Lily Kaplan</a>
  </small>
  <nav>
    <ul>
      
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.instagram.com/lekaps/">Follow Me  <i class="fa fa-instagram"></i></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#"> 
      <%= link_to "LEK", root_path, id: "logo" %>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="page-scroll"><%= link_to "About", root_path(:anchor => 'about')%></li>
        <li><%=link_to "Resume", resume_path%></li> 
        <li><%= link_to "Instagram", instagram_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
 
  </head>
  <body>
    <%= render 'layouts/header' %>

      <%= yield %>
      <%= render 'layouts/footer' %>
 
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">About <i class="fa fa-comment-o"></i>
        </h1>
    </div>
</div>


    <!-- About Section -->
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">About</h2>
                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/1.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>2009-2011</h4>
                                    <h4 class="subheading">Our Humble Beginnings</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/2.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>March 2011</h4>
                                    <h4 class="subheading">An Agency is Born</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/3.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>December 2012</h4>
                                    <h4 class="subheading">Transition to Full Service</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/4.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>July 2014</h4>
                                    <h4 class="subheading">Phase Two Expansion</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <h4>Be Part
                                    <br>Of Our
                                    <br>Story!</h4>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Contact <i class="fa fa-paper-plane-o"></i>
        </h1>
    </div>
</div>

<div class="container">
<p>
  Contact me about this application on my <a href="https://www.linkedin.com/in/lily-kaplan-15b1a558">Linkedin page</a>.
</p>
<p>Reach me via email lekaplan@wesleyan.edu</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron jumbotron-fluid">
  
        <h1 class="display-3">Lily Ellis Kaplan</h1>
            <p class="lead"></p>
   
</div>

<section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1 class="page-header"><span>Where i've been <i class="fa fa-comment-o"></i></span>
                </div>
            </div><!---Row 1--->
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <%=image_tag("bda.jpg", class:"img-circle img-responsive")%>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="subheading">Bermuda to Boston</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">I grew up in Bermuda with my parents, twin sister Hannah, and younger sister Grace, before moving to Lexington, MA</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <%=image_tag("wes_art.jpg", class:"img-circle img-responsive")%>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="subheading">Wesleyan University</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">I graduated from Wesleyan University in Connnecticut, where I played soccer and studied economics and psychology</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                                <%=image_tag("nyc.jpg", class:"img-circle img-responsive")%>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="subheading">New York City</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">I currently live in NYC where I work for Compass, a growth stage real estate startup</p>
                                </div>
                            </div>
                        </li>
                        
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <h4>What
                                    <br>Is
                                    <br>Next!?</h4>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>

<body>
<div class="wrapper">

    <div class="sidebar-wrapper">
        
        <div class="profile-container">
            <%=image_tag("lily.png")%>
                <h1 class="name">Lily Kaplan</h1>
                    <h3 class="tagline">Product Manager @ Compass</h3>
        </div><!--//profile-container-->
            
        <div class="contact-container container-block">
            <ul class="list-unstyled contact-list">
                <li class="email"><i class="fa fa-envelope"></i><a href="mailto: yourname@email.com">lily.ellis.kaplan@gmail.com</a></li>
                <li class="phone"><i class="fa fa-phone"></i><a href="#">781-799-8009</a></li>
                <li class="linkedin"><i class="fa fa-linkedin"></i><a href="https://www.linkedin.com/in/lily-kaplan-15b1a558" target="_blank">linkedin.com/in/lilykaplan</a></li>
                <li class="github"><i class="fa fa-github"></i><a href="https://bitbucket.org/lekaplan/gram_app" target="_blank">github.com/lekaplan</a></li>
             </ul>
        </div><!--//contact-container-->
        
        <div class="education-container container-block">
            <h2 class="container-block-title">Education</h2>
                <div class="item">
                    <h4 class="degree">BA in Psychology</h4>
                        <h5 class="meta">Wesleyan University</h5>
                            <div class="time">2009 - 2013</div>
                </div><!--//item-->
        </div><!--//education-container-->
            
        <div class="volunteer-container container-block">
            <h2 class="container-block-title">Volunteer</h2>
                <ul class="list-unstyled interests-list">
                    <li>Achilles International <span class="lang-desc">Achilles Kids volunteer; 2016 TCS NYC Marathon blind athlete guide</span></li>
                    <li>Girls on the Run<br> <span class="lang-desc">Raised $3K as part of NYC Marathon team</span></li>
                </ul>
        </div><!--//volunteer-->
            
        <div class="interests-container container-block">
            <h2 class="container-block-title">Interests</h2>
                <ul class="list-unstyled interests-list">
                    <li>Running</li>
                    <li>People watching</li>
                    <li>Building things - like this website!</li>
                </ul>
        </div><!--//interests-->
            
    </div><!--//sidebar-wrapper-->
    
   
    
    <div class="main-wrapper">
            
        <section class="section summary-section">
            <h2 class="section-title"><i class="fa fa-user"></i>Summary</h2>
                <div class="summary">
                    <p>I work on the Product team at Compass, a growth-stage real estate technology startup. Prior to Compass, I spent one year in management consulting at CKM Advisors, focusing on leveraging data analytics for technology clients. I have an undergraduate degree from Wesleyan University in Psychology.</p>
                </div><!--//summary-->
        </section><!--//section-->
            
        <section class="section experiences-section">
            <h2 class="section-title"><i class="fa fa-briefcase"></i>Experience</h2>
                
                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Product Manager</h3>
                                <div class="time">2016 - Present</div>
                        </div><!--//upper-row-->
                        <div class="company">Compass, NYC</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>As Compass' first Product Manager focused on internal tools, I am leading the process to align the business and technology components of our business.</p></p>  
                            <ul class = "bullet">
                                <li>Managed full life-cycle of cross-functional Salesforce implementation</li>
                                <li>Participated in vendor selection, managed day-to-day relationship with external consulting partner, defined requirements, developed user stories, conducted user acceptance testing</li>
                                <li>Delivered solution on-time and witin budget</li>
                            </ul>    
                    </div><!--//details-->
                </div><!--//item-->
                
                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Finance Operations & Business Development</h3>
                                <div class="time">2014 - 2015</div>
                        </div><!--//upper-row-->
                        <div class="company">Compass, NYC</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>As part of the Finance and Business Development teams, I led growth-critical projects, working cross-functionally to to bolster finance operations across 5 new markets and grow online lead acquisition.</p>  
                        <p><i>Business Development</i></p>     
                            <ul class = "bullet">
                                 <li>Developed customer acquisition roadmap, built business case for lead generation, and evaluated pilots to improve customer acquisition through paid channels</li>
                                <li>Designed system infrastructure and managed reporting for customer pipeline representing $66 million in property value across 6 regions</li>
                                <li>Led cross-functional effort with engineering and product teams to implement CRM system and optimize site experience for organic lead generation</li>
                           </ul>
                        <p><i>Finance Operations</i></p>    
                            <ul class = "bullet">
                                <li>Analyzed needs of agent finance team to scale operations to 5 new regions with 700 new agents</li>
                                <li>Created dashboards for real-time monitoring of marketing budgets; selected by executive team as example of how to make effective and rapid impacts to the business</li>
                            </ul>
                    </div><!--//details-->
                </div><!--//item-->
                
                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Consultant</h3>
                                <div class="time">2013 - 2014</div>
                        </div><!--//upper-row-->
                        <div class="company">CKM Advisors, NYC</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>CKM Advisors is a consulting firm focused on using data science and analytics to drive operational improvement for technology and financial services clients.</p>
                        <p><i>Operating Costs Analysis for Large University</i></p>
                            <ul class = "bullet">
                                <li>Conducted financial analysis and developed modeling to measure direct and indirect operating costs of satellite institution</li>
                                <li>Analyzed current structure of financial statements and presented recommendations to university president for restructuring of expense allocations across institutional entities</li>
                            </ul>
                        <p><i>IT Service Management Optimization for Fortune 100 Bank</i></p>
                            <ul class = "bullet">
                                <li>Analyzed IT ticket data and identified savings opportunities, providing recommendations for new system design and implementation</li>
                                <li>Defined requirements, developed design and conducted user testing for dashboard application to monitor onboarding activity, yielding a 50% increase in efficiency of targeted HR responses</li>
                            </ul> 
                    </div><!--//details-->
                </div><!--//item-->
                
        </section><!--//main profile section-->
            
           
        <section class="skills-section section">
            <h2 class="section-title"><i class="fa fa-rocket"></i>Skills &amp; Proficiency</h2>
                <div class="skillset"> 
                
                    <div class="item">
                        <h3 class="level-title">Excel</h3>
                            <div class="level-bar">
                                <div class="level-bar-inner" data-level="98%"></div> 
                            </div><!--//level-bar-->                                 
                    </div><!--//item-->
                    
                    <div class="item">
                        <h3 class="level-title">SQL</h3>
                            <div class="level-bar">
                                <div class="level-bar-inner" data-level="75%"></div>  
                            </div><!--//level-bar-->                                 
                    </div><!--//item-->
                    
                    <div class="item">
                        <h3 class="level-title">Javascript</h3>
                            <div class="level-bar">
                                <div class="level-bar-inner" data-level="55%"></div>
                            </div><!--//level-bar-->                                 
                    </div><!--//item-->
                    
                    <div class="item">
                        <h3 class="level-title">HTML5 &amp; CSS</h3>
                            <div class="level-bar">
                                <div class="level-bar-inner" data-level="50%"></div>
                            </div><!--//level-bar-->                                 
                    </div><!--//item-->
                    
                    <div class="item">
                        <h3 class="level-title">Ruby on Rails</h3>
                            <div class="level-bar">
                                <div class="level-bar-inner" data-level="25%"></div>
                            </div><!--//level-bar-->                                 
                    </div><!--//item-->
                
                </div><!--//skillset-->
       
        </section><!--//skills-section-->

</div><!--//main-wrapper-->
</div>